### ISSUE TITLE
MVP 1:  add getRecipes

### ISSUE THREAD

**Issue by SSais** [SchoolOfCode/bc17-w5d1-catch-up-express-api-with-file-storage-green-cakes#1]
Method | Path | Additional Info | Result | Response
-- | -- | -- | -- | --
GET | /api/recipes |   | all recipes | { success: Boolean, payload: recipe array }

getRecipes should return an array of all recipes
```[tasklist]
### Tasks
- [x] add a GET request to path /api/recipes
- [x] Function needs to return all recipes from recipes.json
- [x] The respond need to be in the success/ payload format
- [x] If it fails we should send a 500 error
```
