### ISSUE TITLE
MVP 2: getRecipesById

### ISSUE THREAD

**Issue by Stace0x** [SchoolOfCode/bc17-w5d1-catch-up-express-api-with-file-storage-green-cakes#2]
<html>
<body>

GET | /api/recipes/:id |   | recipes with a particular id if it exists | { success: Boolean, payload: recipe }
-- | -- | -- | -- | --

</body>
</html>
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [x] Create a GET request that will look for the ID in the URL
- [x] create a function that will include the ID params
- [x] match ID's using .findIndex
- [ ] Add a catch error code (406) if wrong ID is requested
```
